-- Create products table with all fields from JSON data
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    description TEXT,
    category VARCHAR(100),
    brand VARCHAR(100),
    supplier VARCHAR(100),
    sku VARCHAR(50),
    barcode VARCHAR(50),
    purchase_price DECIMAL(10,2),
    sale_price DECIMAL(10,2),
    wholesale_price DECIMAL(10,2),
    distributor_price DECIMAL(10,2),
    unit_of_measure VARCHAR(50),
    weight VARCHAR(50),
    dimensions VARCHAR(50),
    color VARCHAR(50),
    size VARCHAR(50),
    material VARCHAR(50),
    tax_rate DECIMAL(5,2),
    tax_category VARCHAR(50),
    track_inventory BOOLEAN DEFAULT FALSE,
    allow_backorder BOOLEAN DEFAULT FALSE,
    min_stock_level INTEGER DEFAULT 0,
    max_stock_level INTEGER,
    reorder_point INTEGER DEFAULT 0,
    reorder_quantity INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT FALSE,
    is_featured BOOLEAN DEFAULT FALSE,
    is_new BOOLEAN DEFAULT FALSE,
    is_on_sale BOOLEAN DEFAULT FALSE,
    age_restricted BOOLEAN DEFAULT FALSE,
    min_age_required INTEGER,
    image_urls TEXT[],  -- PostgreSQL array for image URLs
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    deleted_at TIMESTAMP,
    created_by UUID,
    updated_by UUID
);