export interface Product {
    id: string;
    name: string | null;
    description: string | null;
    category: string | null;
    brand: string | null;
    supplier: string | null;
    sku: string | null;
    barcode: string | null;
    purchase_price: number | null;
    sale_price: number | null;
    wholesale_price: number | null;
    distributor_price: number | null;
    unit_of_measure: string | null;
    weight: string | null;
    dimensions: string | null;
    color: string | null;
    size: string | null;
    material: string | null;
    tax_rate: number | null;
    tax_category: string | null;
    track_inventory: boolean;
    allow_backorder: boolean;
    min_stock_level: number;
    max_stock_level: number | null;
    reorder_point: number;
    reorder_quantity: number;
    is_active: boolean;
    is_featured: boolean;
    is_new: boolean;
    is_on_sale: boolean;
    age_restricted: boolean;
    min_age_required: number | null;
    image_urls: string[];
    // created_at: string | null;
    // updated_at: string | null;
    // deleted_at: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    deleted_at: Date | null;
    created_by: string | null;
    updated_by: string | null;
}